FROM ubuntu:latest
RUN apt-get update
RUN apt-get install apache2 -y
COPY index.html /var/www/html/index.html
RUN chmod  777 /var/www/html
RUN chmod 666 /var/www/html/index.html
CMD ["apache2ctl", "-D", "FOREGROUND"]
