FROM ubuntu:latest
RUN apt update
RUN apt install sudo apt install openjdk-11-jre-headless -y
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz .
RUN tar -xvf apache-tomcat-8.5.99.tar.gz -C /opt
WORKDIR /opt/apache-tomcat-8.5.99
COPY context.xml conf/context.xml
COPY student.war webapps/student.war
COPY mysql-connector.jar lib/mysql-connector.jar
ENTRYPOINT ["/bin/catalina.sh","run"]

